// lib/utils/generateMockAiResponse.ts
import {
  AiAction,
  AiContent,
} from "@/components/documents/view/DocumentWorkspace";

export function generateMockAiResponse(
  action: AiAction,
  text: string
): AiContent {
  switch (action) {
    case "summarize":
      return {
        type: "summarize",
        data: `This is a mock summary of the selected text: "${text.substring(
          0,
          50
        )}...". In a real application, this would be a concise summary generated by a large language model.`,
        sourceText: text,
      };
    case "explain":
      return {
        type: "explain",
        data: `Here is a simplified explanation for "${text.substring(
          0,
          50
        )}...". The core idea is broken down into simpler terms for better understanding. This response is a placeholder.`,
        sourceText: text,
      };
    case "quiz":
      return {
        type: "quiz",
        data: [
          {
            question: `What is the main principle described in "${text.substring(
              0,
              30
            )}..."?`,
            answer: "Mock Answer 1",
          },
          {
            question: `How does this relate to the broader topic?`,
            answer: "Mock Answer 2",
          },
        ],
        sourceText: text,
      };
    case "ask":
      return {
        type: "ask",
        data: null, // The 'ask' action just opens the chat interface
      };
    default:
      return null;
  }
}
